RUN:
  DATA: shakespeare.txt
  CUDA: yes
  OUTPUT_DIR: ./25000
MODEL:
  CLASS: Transformer
  PARAMS:
    CONTEXT_SIZE: 256
    EMBEDDING_SIZE: 384
    NUM_HEADS: 6
    NUM_BLOCKS: 6
    DROPOUT_RATIO: 0.2
TRAIN:
  NUM_ITERS: 25000
  LEARNING_RATE: 1e-3
  BATCH_SIZE: 64
  CHECKPOINT_ITERS: 2500
EVAL:
  CADENCE_ITERS: 100
  NUM_SAMPLES: 50
  GENERATION_ITERS: 500
  GENERATION_SIZE: 2000
